language: node_js
node_js:
  - 9
  - 8

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: cross-env CI=1 react-scripts test --env=jsdom --coverage --coverageReporters=text-lcov | coveralls
